package Aph.DAO.Impl.UI;

import Aph.Citerne;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CiterneUI.java
 *
 * Created on Dec 19, 2010, 3:45:13 PM
 */
/**
 *
 * @author Medard
 */
public class CiterneUI extends javax.swing.JFrame {

    private DAOS daos;
    private int currentRow;
    private ArrayList<Integer> ids = new ArrayList<Integer>();
    private DefaultListModel listmodel = new DefaultListModel();
    private boolean listLoad;
    private boolean saveOrUpdate;
    private Citerne citerne;
    private String critère;
    private Gestion_Citerne gestCit;

    /** Creates new form CiterneUI */
    public CiterneUI() {
        initComponents();
        this.setTitle("Citernes");
        daos = new DAOS();
    }

    public DAOS getDaos() {
        return daos;
    }

    public Gestion_Citerne getGestCit() {
        return gestCit;
    }

    public void setGestCit(Gestion_Citerne gestCit) {
        this.gestCit = gestCit;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCiterne = new javax.swing.JList();
        txtNom = new javax.swing.JTextField();
        txtCapacité = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();
        btnEffacer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        cbxSearch = new javax.swing.JComboBox();
        txtSearch = new javax.swing.JTextField();
        btnChercher = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lstCiterne.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstCiterne.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCiterneValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCiterne);

        jLabel1.setText("Nom");

        jLabel2.setText("Capacité");

        jLabel5.setFont(new java.awt.Font("Colonna MT", 3, 24));
        jLabel5.setText("Citerne");

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnEnregistrer.setText("Enregistre");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        btnPrevious.setText("<");

        btnNext.setText(">");

        jLabel4.setText("Rechercher");

        cbxSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionner critère", "Nom", "Tout" }));
        cbxSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSearchActionPerformed(evt);
            }
        });

        btnChercher.setText("Chercher");
        btnChercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChercherActionPerformed(evt);
            }
        });

        jLabel3.setText("m³");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNom)
                                    .addComponent(txtCapacité, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAjouter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModifier)
                                .addGap(6, 6, 6)
                                .addComponent(btnEnregistrer)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEffacer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnnuler))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChercher)
                .addContainerGap(163, Short.MAX_VALUE))
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAjouter, btnAnnuler, btnEffacer, btnEnregistrer, btnModifier});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnNext, btnPrevious});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrevious)
                            .addComponent(btnNext))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCapacité, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAjouter)
                            .addComponent(btnModifier)
                            .addComponent(btnEnregistrer)
                            .addComponent(btnEffacer)
                            .addComponent(btnAnnuler))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChercher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        txtNom.setText("");
        txtCapacité.setText("");
        txtNom.requestFocus();
        currentRow = lstCiterne.getSelectedIndex();
        buttonEnabler(false);
        saveOrUpdate = true;
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        listLoad = false;
        Citerne cit;
        if (saveOrUpdate) {
            cit = new Citerne(txtNom.getText(), Double.parseDouble(txtCapacité.getText()));
            Citerne newCiterne = getDaos().getCiterneDAO().createCiterne(cit);
            if (newCiterne != null) {
                JOptionPane.showMessageDialog(null, "Enregistrement efféctuée.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
                this.getGestCit().formRefresh();
            }
        } else {
            cit = getDaos().getCiterneDAO().getCiterneById(citerne.getId());
            cit.setName(txtNom.getText());
            cit.setCapacity(Double.parseDouble(txtCapacité.getText()));
            boolean updated = getDaos().getCiterneDAO().updateCiterne(cit);
            if (updated) {
                JOptionPane.showMessageDialog(null, "Modification efféctuée.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
                this.getGestCit().formRefresh();
            }
        }
        listDisplay(getDaos().getCiterneDAO().getAllCiterne());
        listLoad = true;
        lstCiterne.setSelectedValue(cit.getName(), true);
        buttonEnabler(true);
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        buttonEnabler(false);
        saveOrUpdate = false;
        currentRow = lstCiterne.getSelectedIndex();
        txtNom.requestFocus();
    }//GEN-LAST:event_btnModifierActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        List<Citerne> citernes = getDaos().getCiterneDAO().getAllCiterne();
        listDisplay(citernes);
        lstCiterne.setSelectedIndex(0);
        listDetails();
        buttonEnabler(true);
        listLoad = true;
    }//GEN-LAST:event_formWindowOpened

    private void lstCiterneValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCiterneValueChanged
        if (listLoad == true) {
            listDetails();
        }
    }//GEN-LAST:event_lstCiterneValueChanged

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer le citerne " + lstCiterne.getSelectedValue().toString() + "?", "Confirmez", JOptionPane.YES_NO_CANCEL_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            boolean deleted = getDaos().getCiterneDAO().deleteCiterne(citerne.getId());
            if (deleted) {
                JOptionPane.showMessageDialog(null, "Suppression efféctuée", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            }
            listLoad = false;
            lstCiterne.setSelectedIndex(0);
            listDetails();
            listLoad = true;
            lstCiterne.requestFocus();
            buttonEnabler(true);
        }
    }//GEN-LAST:event_btnEffacerActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        buttonEnabler(true);
        listLoad = true;
        lstCiterne.setSelectedIndex(currentRow);
        lstCiterne.requestFocus();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void cbxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSearchActionPerformed
        critère = cbxSearch.getSelectedItem().toString();
    }//GEN-LAST:event_cbxSearchActionPerformed

    private void btnChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChercherActionPerformed
        listLoad = false;
        if (critère.equals("Sélectionner critère")) {
            JOptionPane.showMessageDialog(null, "Précisez le critère de recherche.", "Attention", JOptionPane.ERROR_MESSAGE);
        } else if (critère.equals("Nom")) {
            List<Citerne> found = new ArrayList<Citerne>();
            found.add(getDaos().getCiterneDAO().getCiterneByName(txtSearch.getText()));
            listDisplay(found);
            lstCiterne.setSelectedIndex(0);
            listDetails();
        } else if (critère.equals("Tout")) {
            List<Citerne> found = getDaos().getCiterneDAO().getAllCiterne();
            listDisplay(found);
            lstCiterne.setSelectedIndex(0);
            listDetails();
        }
    }//GEN-LAST:event_btnChercherActionPerformed

    public void buttonEnabler(boolean enabler) {
        btnEnregistrer.setEnabled(!enabler);
        btnAnnuler.setEnabled(!enabler);
        btnAjouter.setEnabled(enabler);
        btnModifier.setEnabled(enabler);
        btnEffacer.setEnabled(enabler);
        btnChercher.setEnabled(enabler);
        btnPrevious.setEnabled(enabler);
        btnNext.setEnabled(enabler);
    }

    public void listDisplay(List<Citerne> cits) {
        ids.clear();
        listmodel.clear();
        for (Citerne cit : cits) {
            listmodel.addElement(cit.getName());
            ids.add(cit.getId());
        }
        lstCiterne.setModel(listmodel);
    }

    public void listDetails() {
        citerne = new Citerne();
        int citIndex = lstCiterne.getSelectedIndex();
        int citId = ids.get(citIndex);
        citerne = getDaos().getCiterneDAO().getCiterneById(citId);
        fillIn(citerne);
    }

    public void fillIn(Citerne cit) {
        txtNom.setText(cit.getName());
        txtCapacité.setText(Double.toString(cit.getCapacity()));
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnChercher;
    private javax.swing.JButton btnEffacer;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JComboBox cbxSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList lstCiterne;
    private javax.swing.JTextField txtCapacité;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
