/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DensitéUI.java
 *
 * Created on Dec 29, 2010, 5:15:34 PM
 */
package Aph.DAO.Impl.UI;

import Aph.Densité;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Medard
 */
public class DensitéUI extends javax.swing.JFrame {

    private DefaultListModel listModel = new DefaultListModel();
    private Object[] columnNames;
    private DAOS daos;
    private boolean listLoad, saveOrUpdate;
    private List<Integer> ids = new ArrayList<Integer>();
    private Densité densité;
    private int currentRow;

    /** Creates new form DensitéUI */
    public DensitéUI() {
        initComponents();
        this.setTitle("Densités");
        daos = new DAOS();
    }

    public DAOS getDaos() {
        return daos;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstDensités = new javax.swing.JList();
        txtNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();
        btnEffacer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsom = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnModifier = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lstDensités.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDensités.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstDensitésValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstDensités);

        jLabel1.setText("Nom:");

        jLabel2.setFont(new java.awt.Font("Colonna MT", 3, 24));
        jLabel2.setText("Densités");

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        tblConsom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Produit", "Consommation(kg/min)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblConsom);
        tblConsom.getColumnModel().getColumn(1).setCellEditor(null);

        jLabel4.setText("Teneur en produits:");

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnregistrer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEffacer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnnuler))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(6, 6, 6)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAjouter, btnAnnuler, btnEffacer, btnEnregistrer, btnModifier});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter)
                    .addComponent(btnModifier)
                    .addComponent(btnEnregistrer)
                    .addComponent(btnEffacer)
                    .addComponent(btnAnnuler))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        buttonEnabler(false);
        txtNom.setText("");
        for (int i = 0; i < tblConsom.getRowCount(); i++) {
            tblConsom.setValueAt("", i, 1);
        }
        saveOrUpdate = true;
        txtNom.requestFocus();
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        Densité dens = new Densité();
        listLoad = false;
        Object[][] consom = new Object[tblConsom.getRowCount()][2];
        for (int i = 0; i < tblConsom.getRowCount(); i++) {
          //  consom[i][0] = tblConsom.getModel().setValueAt(, WIDTH, currentRow)
            consom[i][1] = tblConsom.getValueAt(i, 1);
        }
        if (saveOrUpdate) {
            dens = new Densité(txtNom.getText(), consom);
            getDaos().getDensitéDAO().createDensité(dens);
            JOptionPane.showMessageDialog(null, "Enregistrement efféctué", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
        } else {
            dens = getDaos().getDensitéDAO().getDensitéById(ids.get(lstDensités.getSelectedIndex()));
            dens.setName(txtNom.getText());
            dens.setConsommation(consom);
            dens.setConsRowNum(tblConsom.getRowCount());
            boolean updated = getDaos().getDensitéDAO().updateDensité(densité, null);
            if (updated) {
                JOptionPane.showMessageDialog(null, "Modification efféctuée.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        listDisplay(getDaos().getDensitéDAO().getAllDensité());
        listLoad = true;
        lstDensités.setSelectedValue(dens.getName(), true);
        lstDensités.requestFocus();
        buttonEnabler(true);
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        List<Densité> allDensités = getDaos().getDensitéDAO().getAllDensité();
        listDisplay(allDensités);
        listLoad = false;
        lstDensités.setSelectedIndex(0);
        listDetails();
        listLoad = true;
        lstDensités.requestFocus();
        buttonEnabler(true);
    }//GEN-LAST:event_formWindowOpened

    private void lstDensitésValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstDensitésValueChanged
        if (listLoad == true) {
            listDetails();
        }
    }//GEN-LAST:event_lstDensitésValueChanged

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        buttonEnabler(false);
        saveOrUpdate = false;
        currentRow = lstDensités.getSelectedIndex();
        txtNom.requestFocus();
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        buttonEnabler(true);
        lstDensités.setSelectedIndex(currentRow);
        lstDensités.requestFocus();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer la densité " + getDaos().getDensitéDAO().getDensitéById(ids.get(lstDensités.getSelectedIndex())).getName(), "Confirmez", JOptionPane.YES_NO_CANCEL_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            boolean deleted = getDaos().getDensitéDAO().deleteDensité(getDaos().getDensitéDAO().getDensitéById(ids.get(lstDensités.getSelectedIndex())).getId());
            if (deleted) {
                JOptionPane.showMessageDialog(null, "Suppression efféctuée.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEffacerActionPerformed

    public void listDisplay(List<Densité> densités) {
        ids.clear();
        listModel.clear();
        for (Densité dens : densités) {
            listModel.addElement(dens.getName());
            ids.add(dens.getId());
        }
        lstDensités.setModel(listModel);
    }

    public void listDetails() {
        densité = new Densité();
        int densIndex = lstDensités.getSelectedIndex();
        int densId = ids.get(densIndex);
        densité = getDaos().getDensitéDAO().getDensitéById(densId);
        fillIn(densité);
    }

    public void fillIn(Densité dens) {
        columnNames = new Object[2];
        columnNames[0] = tblConsom.getColumnName(0);
        columnNames[1] = tblConsom.getColumnName(1);
        txtNom.setText(dens.getName());
        tblConsom.setModel(new DefaultTableModel(dens.getConsommation(), columnNames));
    }

    public void buttonEnabler(boolean enabler) {
        btnAjouter.setEnabled(enabler);
        btnModifier.setEnabled(enabler);
        btnEffacer.setEnabled(enabler);
        btnEnregistrer.setEnabled(!enabler);
        btnAnnuler.setEnabled(!enabler);
        tblConsom.setEnabled(!enabler);
        txtNom.setEditable(!enabler);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEffacer;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList lstDensités;
    private javax.swing.JTable tblConsom;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
