/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Gestion_blocks.java
 *
 * Created on Jan 12, 2011, 11:33:02 PM
 */
package Aph.DAO.Impl.UI;

import Aph.BlockDélivré;
import Aph.ProduitSemiFini;
import Aph.Technicien;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Medard
 */
public class Gestion_blocks extends javax.swing.JFrame {

    private String déstination, retirantBlock;
    private ProduitSemiFiniUI produitSemiFiniUI = new ProduitSemiFiniUI();
    private DensitéUI densitéUI = new DensitéUI();
    private ProductionUI productionUI = new ProductionUI();
    private TechnicienBlockUI technicienUI = new TechnicienBlockUI();
    private DAOS daos;
    private Object[][] blockDetails;
    private Object[] columnNamesStock;
    private List<Integer> retirantIds = new ArrayList<Integer>();
    private List<Integer> blockIds = new ArrayList<Integer>();
    private boolean tableLoad;
    private HistoriqueBlockUI histBlockUI = new HistoriqueBlockUI();
    private signInUI signIn;

    /** Creates new form Gestion_blocks */
    public Gestion_blocks() {
        initComponents();
        daos = new DAOS();
        buttonEnabler(true);
        densitéUI.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        productionUI.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        produitSemiFiniUI.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        technicienUI.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        histBlockUI.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle("Gestion des blocks");
        tblBlocks.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblBlocks.getSelectionModel().addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                tblBlocksValueChanged(evt);
            }
        });
        List<Technicien> techs = daos.getTechnicienDAO().getAllTechniciens();
        for (Technicien tech : techs) {
            cbxBlockRetirant.addItem(tech.getLastName().concat(" " + tech.getFirstName()));
            retirantIds.add(tech.getId());
        }
    }

    public signInUI getSignIn() {
        return signIn;
    }

    public void setSignIn(signInUI signIn) {
        this.signIn = signIn;
    }

    public DAOS getDaos() {
        return daos;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNvlLivraison = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnLivrer = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnDéconnecter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbxDéstination = new javax.swing.JComboBox();
        btnOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBlocks = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtSéctions = new javax.swing.JTextField();
        lblDensité = new javax.swing.JLabel();
        cbxBlockRetirant = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        btnHistorique = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnNvlLivraison.setText("Nouvel livraison");
        btnNvlLivraison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNvlLivraisonActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler livraison");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        btnLivrer.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        btnLivrer.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnLivrer.setText("Livrer");
        btnLivrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivrerActionPerformed(evt);
            }
        });

        btnDéconnecter.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        btnDéconnecter.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnDéconnecter.setText("Déconnecter");
        btnDéconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDéconnecterActionPerformed(evt);
            }
        });

        jLabel1.setText("Aller à:");

        cbxDéstination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionner déstination", "Productions", "Densités", "Produits semi-finis", "Techniciens", "Quitter" }));
        cbxDéstination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDéstinationActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Blocks en stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        tblBlocks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Densité", "Poids total", "Dimension total", "Nombre de séctions"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBlocks);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Livraison", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        cbxBlockRetirant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionner retirant" }));
        cbxBlockRetirant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBlockRetirantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDensité, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSéctions, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxBlockRetirant, 0, 136, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbxBlockRetirant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSéctions))
                    .addComponent(lblDensité, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(204, 0, 0), new java.awt.Color(255, 255, 0)));

        btnHistorique.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        btnHistorique.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnHistorique.setForeground(new java.awt.Color(0, 51, 51));
        btnHistorique.setText("Historique");
        btnHistorique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHistorique)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLivrer, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(btnAnnuler)
                            .addComponent(btnNvlLivraison)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxDéstination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                        .addComponent(btnDéconnecter)))
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnnuler, btnDéconnecter, btnLivrer, btnNvlLivraison, jSeparator1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNvlLivraison)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnnuler)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLivrer))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxDéstination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK)
                    .addComponent(btnDéconnecter))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBlocksValueChanged(javax.swing.event.ListSelectionEvent evt) {
        if (tableLoad = true) {
            tableDetails();
        }
    }
    private void cbxDéstinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDéstinationActionPerformed
        déstination = cbxDéstination.getSelectedItem().toString();
    }//GEN-LAST:event_cbxDéstinationActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (déstination.equals("Sélectionner déstination")) {
            JOptionPane.showMessageDialog(null, "Sélectionnez une déstination S.V.P", "Halte", JOptionPane.ERROR_MESSAGE);
        } else if (déstination.equals("Productions")) {
            productionUI.setVisible(true);
        } else if (déstination.equals("Densités")) {
            densitéUI.setVisible(true);
        } else if (déstination.equals("Produits semi-finis")) {
            produitSemiFiniUI.setVisible(true);
            produitSemiFiniUI.setGetsBlock(this);
        } else if (déstination.equals("Techniciens")) {
            technicienUI.setVisible(true);
        } else if (déstination.equals("Quitter")) {
            int i = JOptionPane.showConfirmDialog(null, "Voulez-vous quitter l'application?", "Confirmer", JOptionPane.YES_NO_CANCEL_OPTION);
            if (i == JOptionPane.YES_OPTION) {
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        refreshForm();
    }//GEN-LAST:event_formWindowOpened

    private void btnNvlLivraisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNvlLivraisonActionPerformed
        buttonEnabler(false);
    }//GEN-LAST:event_btnNvlLivraisonActionPerformed

    private void btnDéconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDéconnecterActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Voulez-vous quitter l'application?", "Confirmez", JOptionPane.YES_NO_CANCEL_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            this.getSignIn().getPswdMotDePasse().setText("");
            this.setVisible(false);
        } else {
            tblBlocks.requestFocus();
        }
    }//GEN-LAST:event_btnDéconnecterActionPerformed

    private void btnHistoriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriqueActionPerformed
        histBlockUI.setVisible(true);
    }//GEN-LAST:event_btnHistoriqueActionPerformed

    private void btnLivrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivrerActionPerformed
        if (txtSéctions.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Précisez combien de séctions vous voulez livrer.", "Attention", JOptionPane.ERROR_MESSAGE);
        } else if (lblDensité.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Sélectionnez le block à livrer.", "Attention", JOptionPane.ERROR_MESSAGE);
        } else if (tblBlocks.getModel().getValueAt(tblBlocks.getSelectedRow(), 3).toString().equals("-")) {
            JOptionPane.showMessageDialog(null, "Précisez le nombre de séctions de " + tblBlocks.getModel().getValueAt(tblBlocks.getSelectedRow(), 0) + " dans le stock.", "Attention", JOptionPane.ERROR_MESSAGE);
        } else if (retirantBlock.equals("Sélectionner retirant")) {
            JOptionPane.showMessageDialog(null, "Précisez le nom du retirant.", "Attention", JOptionPane.ERROR_MESSAGE);
        } else {
            BlockDélivré block = new BlockDélivré(getDaos().getTechnicienDAO().getTechnicienById(retirantIds.get(cbxBlockRetirant.getSelectedIndex() - 1)).getId(), getDaos().getProduitSemiFiniDAO().getProduitSemiFiniById(blockIds.get(tblBlocks.getSelectedRow())).getId(), Integer.parseInt(txtSéctions.getText()));
            ProduitSemiFini prod = getDaos().getProduitSemiFiniDAO().getProduitSemiFiniById(block.getBlock_id());
            if (prod.getNbrSections() >= block.getNumberSections()) {
                BlockDélivré returned = getDaos().getBlockDélivréDAO().createBlockDélivré(block);
                if (returned != null) {
                    JOptionPane.showMessageDialog(null, "Livraison réussie.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Livraison échouée.", "Erreur de livraison", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Vous n'avez pas assez de " + lblDensité.getText() + " en stock.", "Attention", JOptionPane.ERROR_MESSAGE);
            }
        }
        List<ProduitSemiFini> blocks = getDaos().getProduitSemiFiniDAO().getAllProduitSemiFini();
        tableLoad = false;
        tableDisplay(blocks);
        tableLoad = true;
        cbxBlockRetirant.setSelectedIndex(0);
        lblDensité.setText("");
        buttonEnabler(true);
    }//GEN-LAST:event_btnLivrerActionPerformed

    private void cbxBlockRetirantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBlockRetirantActionPerformed
        retirantBlock = cbxBlockRetirant.getSelectedItem().toString();
    }//GEN-LAST:event_cbxBlockRetirantActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        buttonEnabler(true);
        txtSéctions.setText("");
    }//GEN-LAST:event_btnAnnulerActionPerformed
    private void buttonEnabler(boolean enabler) {
        btnNvlLivraison.setEnabled(enabler);
        btnDéconnecter.setEnabled(enabler);
        btnAnnuler.setEnabled(!enabler);
        btnLivrer.setEnabled(!enabler);
        btnHistorique.setEnabled(enabler);
        txtSéctions.setEnabled(!enabler);
        cbxBlockRetirant.setEnabled(!enabler);
    }

    public void tableDisplay(List<ProduitSemiFini> blocks) {
        columnNamesStock = new Object[tblBlocks.getColumnCount()];
        for (int i = 0; i < tblBlocks.getColumnCount(); i++) {
            columnNamesStock[i] = tblBlocks.getColumnName(i);
        }
        blockDetails = new Object[blocks.size()][tblBlocks.getColumnCount()];

        for (int i = 0; i < blocks.size(); i++) {
            blockDetails[i][0] = getDaos().getDensitéDAO().getDensitéById(blocks.get(i).getDensityId()).getName();
            blockDetails[i][1] = blocks.get(i).getPoids();
            blockDetails[i][2] = blocks.get(i).getDimension();
            if (!Integer.toString(blocks.get(i).getNbrSections()).equals("NULL")) {
                blockDetails[i][3] = blocks.get(i).getNbrSections();
            } else {
                blockDetails[i][3] = "-";
            }
            blockIds.add(blocks.get(i).getId());
        }
        tblBlocks.setModel(new DefaultTableModel(blockDetails, columnNamesStock));
    }

    public void tableDetails() {
        ProduitSemiFini produit = null;
        int selectedRow = tblBlocks.getSelectedRow();

        try {
            if (selectedRow != -1) {
                produit = getDaos().getProduitSemiFiniDAO().getProduitSemiFiniById(blockIds.get(tblBlocks.getSelectedRow()));
            } else {
                produit = getDaos().getProduitSemiFiniDAO().getProduitSemiFiniById(blockIds.get(0));
            }
        } catch (NullPointerException e) {
            produit = getDaos().getProduitSemiFiniDAO().getProduitSemiFiniById(blockIds.get(0));
        }
        lblDensité.setText(produit.getName());
    }

    public void refreshForm() {
        List<ProduitSemiFini> blocks = new ArrayList<ProduitSemiFini>();
        blocks = getDaos().getProduitSemiFiniDAO().getAllProduitSemiFini();
        tableDisplay(blocks);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnDéconnecter;
    private javax.swing.JButton btnHistorique;
    private javax.swing.JButton btnLivrer;
    private javax.swing.JButton btnNvlLivraison;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cbxBlockRetirant;
    private javax.swing.JComboBox cbxDéstination;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDensité;
    private javax.swing.JTable tblBlocks;
    private javax.swing.JTextField txtSéctions;
    // End of variables declaration//GEN-END:variables
}
