/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Gestion_Produit.java
 *
 * Created on Jan 8, 2011, 11:17:15 PM
 */
package Aph.DAO.Impl.UI;

import Aph.DAO.Impl.TechnicienProduitDAOImpl;
import Aph.MatièrePremière;
import Aph.ProduitDélivré;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Medard
 */
public class Gestion_Produit extends javax.swing.JFrame {

    private DAOS daos;
    private boolean listLoad, periodValidator;
    private DefaultListModel listModel = new DefaultListModel();
    private DefaultTableModel stockTblModel, histTblModel, totalTblModel;
    private List<Integer> ids = new ArrayList<Integer>();
    private List<Integer> techIds = new ArrayList<Integer>();
    private String selectedDestination, retirantName, retirantNameTri;
    private MatièrePremièreUI matièrePremièreUI = new MatièrePremièreUI();
    private TechnicienProdUI technicienProdUI = new TechnicienProdUI();
    private TechnicienProduitDAOImpl techDAOImpl = new TechnicienProduitDAOImpl();
    private double livraisonTtl, quantDispoTotal;
    private Object[] columnTotal;
    private Object[][] totalData;
    private int rowNum;
    private DateFormat ft;

    /** Creates new form Gestion_Produit */
    public Gestion_Produit() {
        initComponents();
        daos = new DAOS();
        rowNum = 0;
        tblTotal.setEnabled(false);
        dtSince.setEnabled(false);
        dtUntil.setEnabled(false);
        cbxRetirantTri.setEnabled(false);
        matièrePremièreUI.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        technicienProdUI.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle("Gestion des produits");
        for (int i = 0; i < techDAOImpl.getTechnicienCount(); i++) {
            cbxRetirant.addItem(techDAOImpl.getAllTechniciens().get(i).getLastName().concat(" " + techDAOImpl.getAllTechniciens().get(i).getFirstName()));
            cbxRetirantTri.addItem(techDAOImpl.getAllTechniciens().get(i).getLastName().concat(" " + techDAOImpl.getAllTechniciens().get(i).getFirstName()));
            techIds.add(techDAOImpl.getAllTechniciens().get(i).getId());
        }
        cbxRetirant.setEnabled(false);
        tblTotalInit();
        ft = DateFormat.getDateInstance(DateFormat.LONG, Locale.UK);
        dtSince.setDateFormat(ft);
        dtUntil.setDateFormat(ft);
        periodValidator = false;
    }

    public DAOS getDaos() {
        return daos;
    }

    public JList getLstStock() {
        return lstStock;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstStock = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtLivraison = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        cbxRetirant = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTotal = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxAllerA = new javax.swing.JComboBox();
        btnOK = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        btnAnnuler = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnLivrer = new javax.swing.JButton();
        btnNvlLivraison = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblHistorique = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        btnOkTri = new javax.swing.JButton();
        pnlDateTri = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        dtUntil = new datechooser.beans.DateChooserCombo();
        jLabel4 = new javax.swing.JLabel();
        dtSince = new datechooser.beans.DateChooserCombo();
        pnlRetirantTri = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbxRetirantTri = new javax.swing.JComboBox();
        chbxDateTri = new javax.swing.JCheckBox();
        chbxRetirantTri = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        lstStock.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstStock.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstStockValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstStock);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Produit", "Origine", "Date de production", "Date d'expiration", "Quantité(Litres)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblDetails);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Livraison", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLivraison, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLivraison, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Livraison total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        cbxRetirant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionner un nom" }));
        cbxRetirant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRetirantActionPerformed(evt);
            }
        });

        tblTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "N.", "Produit", "Quantité(Litres)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblTotal);
        tblTotal.getColumnModel().getColumn(0).setPreferredWidth(1);
        tblTotal.getColumnModel().getColumn(2).setPreferredWidth(20);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxRetirant, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(cbxRetirant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modifications", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel2.setText("Aller à:");

        cbxAllerA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionner déstination", "Modifier stock", "Modifier retirants autorisés", "Quitter" }));
        cbxAllerA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAllerAActionPerformed(evt);
            }
        });

        btnOK.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxAllerA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxAllerA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK))
                .addContainerGap())
        );

        btnAnnuler.setFont(new java.awt.Font("Tahoma", 2, 11));
        btnAnnuler.setText("Annuler livraison");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        btnLivrer.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        btnLivrer.setFont(new java.awt.Font("Tahoma", 1, 12));
        btnLivrer.setText("Livrer");
        btnLivrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLivrerActionPerformed(evt);
            }
        });

        btnNvlLivraison.setFont(new java.awt.Font("Tahoma", 2, 11));
        btnNvlLivraison.setText("Nouvel livraison");
        btnNvlLivraison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNvlLivraisonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNvlLivraison, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(btnLivrer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(btnAnnuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel11Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnnuler, btnLivrer, btnNvlLivraison});

        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnNvlLivraison)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnnuler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnLivrer)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel3, jPanel4});

        jTabbedPane1.addTab("Stock", jPanel1);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Historique générale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N

        tblHistorique.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Retirant", "Produit", "Quantité", "Date de retrait"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblHistorique);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tri rafiné par date et/ou retirant", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        btnOkTri.setText("OK");
        btnOkTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkTriActionPerformed(evt);
            }
        });

        pnlDateTri.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("De");

        jLabel4.setText("à");

        javax.swing.GroupLayout pnlDateTriLayout = new javax.swing.GroupLayout(pnlDateTri);
        pnlDateTri.setLayout(pnlDateTriLayout);
        pnlDateTriLayout.setHorizontalGroup(
            pnlDateTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDateTriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDateTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDateTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dtUntil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dtSince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlDateTriLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dtSince, dtUntil});

        pnlDateTriLayout.setVerticalGroup(
            pnlDateTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDateTriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDateTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(dtSince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlDateTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDateTriLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(dtUntil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDateTriLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4)))
                .addContainerGap())
        );

        pnlRetirantTri.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Retirant");

        cbxRetirantTri.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tous les retirants" }));
        cbxRetirantTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRetirantTriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRetirantTriLayout = new javax.swing.GroupLayout(pnlRetirantTri);
        pnlRetirantTri.setLayout(pnlRetirantTriLayout);
        pnlRetirantTriLayout.setHorizontalGroup(
            pnlRetirantTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRetirantTriLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxRetirantTri, 0, 155, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlRetirantTriLayout.setVerticalGroup(
            pnlRetirantTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRetirantTriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRetirantTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxRetirantTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        chbxDateTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxDateTriActionPerformed(evt);
            }
        });

        chbxRetirantTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxRetirantTriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addComponent(chbxDateTri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlDateTri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel9Layout.createSequentialGroup()
                        .addComponent(chbxRetirantTri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlRetirantTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnOkTri)
                .addContainerGap())
        );

        jPanel9Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pnlDateTri, pnlRetirantTri});

        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(chbxDateTri)
                            .addComponent(pnlDateTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(chbxRetirantTri)
                            .addComponent(pnlRetirantTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btnOkTri)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imprimer ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        btnPrint.setText("Imprimer");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrint)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrint)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        jTabbedPane1.addTab("Historique", jPanel2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        List<MatièrePremière> produits = getDaos().getMatièrePremièreDAO().getAllMatièrePremière();
        List<ProduitDélivré> prods = getDaos().getProduitDélivréDAO().getAllProduitDélivré();
        listDisplay(produits);
        listDisplayDelv(prods);
        listLoad = true;
        lstStock.setSelectedIndex(0);
        listDetails();
        lstStock.requestFocus();
        buttonEnabler(true);
    }//GEN-LAST:event_formWindowOpened

    private void lstStockValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstStockValueChanged
        if (listLoad == true) {
            listDetails();
        }
    }//GEN-LAST:event_lstStockValueChanged

    private void cbxAllerAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAllerAActionPerformed
        selectedDestination = cbxAllerA.getSelectedItem().toString();
    }//GEN-LAST:event_cbxAllerAActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (selectedDestination.equals("Sélectionner déstination")) {
            JOptionPane.showMessageDialog(null, "Sélectionnez une déstination SVP.", "Halte", JOptionPane.ERROR_MESSAGE);
        } else if (selectedDestination.equals("Modifier stock")) {
            matièrePremièreUI.setVisible(true);
            matièrePremièreUI.setGetsProd(this);
        } else if (selectedDestination.equals("Modifier retirants autorisés")) {
            technicienProdUI.setVisible(true);
        } else if (selectedDestination.equals("Quitter")) {
            int i = JOptionPane.showConfirmDialog(null, "Voullez-vous quitter l'application?", "Confirmez", JOptionPane.YES_NO_CANCEL_OPTION);
            if (i == JOptionPane.YES_OPTION) {
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        cbxRetirant.setSelectedIndex(0);
        if (!txtLivraison.getText().isEmpty()) {
            try {
                if (Double.parseDouble(txtLivraison.getText()) <= quantDispoTotal) {
                    ++rowNum;
                    cbxRetirant.setEnabled(true);
                    livraisonTtl += Double.parseDouble(txtLivraison.getText());
                    Object[] row = new Object[tblTotal.getColumnCount()];
                    row[0] = rowNum;
                    row[1] = lstStock.getSelectedValue().toString();
                    row[2] = txtLivraison.getText();
                    totalTblModel.addRow(row);
                    tblTotal.setModel(totalTblModel);
                    txtLivraison.setText("");
                } else {
                    JOptionPane.showMessageDialog(null, "Vous n'avez que " + quantDispoTotal + " litres de " + lstStock.getSelectedValue().toString() + " disponible.", "Attention", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Entrez une valuer numérique SVP.", "Attention", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Précisez combien de litres de " + lstStock.getSelectedValue().toString() + " vous voulez délivrer.", selectedDestination, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnNvlLivraisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNvlLivraisonActionPerformed
        buttonEnabler(false);
    }//GEN-LAST:event_btnNvlLivraisonActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        buttonEnabler(true);
        tblTotalInit();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnLivrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLivrerActionPerformed
        if (tblTotal.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Précisez bien le produit à délivrér.", "Attention", JOptionPane.ERROR_MESSAGE);
        } else if (retirantName.equals("Sélectionner un nom")) {
            JOptionPane.showMessageDialog(null, "Sélectionner le nom du retirant SVP!", "Attention", JOptionPane.ERROR_MESSAGE);
        } else {
            for (int idx = 0; idx < tblTotal.getModel().getRowCount(); idx++) {
                ProduitDélivré prod = new ProduitDélivré(techDAOImpl.getTechnicienById(techIds.get(cbxRetirant.getSelectedIndex() - 1)).getId(),
                        getDaos().getMatièrePremièreDAO().getMatièrePremièreByName(tblTotal.getModel().getValueAt(idx, 1).toString()).get(0).getProductId(), Double.parseDouble(tblTotal.getModel().getValueAt(idx, 2).toString()));
                getDaos().getProduitDélivréDAO().createProduitDélivré(prod);
            }
            JOptionPane.showMessageDialog(null, "Livraison efféctuée", "Efféctué", JOptionPane.INFORMATION_MESSAGE);
            buttonEnabler(true);
            tblTotalInit();
            listLoad = false;
            listDisplayDelv(getDaos().getProduitDélivréDAO().getAllProduitDélivré());
            listDisplay(getDaos().getMatièrePremièreDAO().getAllMatièrePremière());
            listLoad = true;
            lstStock.setSelectedIndex(0);
            listDetails();
        }
    }//GEN-LAST:event_btnLivrerActionPerformed

    private void cbxRetirantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRetirantActionPerformed
        retirantName = cbxRetirant.getSelectedItem().toString();
    }//GEN-LAST:event_cbxRetirantActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        Reports view = new Reports();
        if (!chbxDateTri.isSelected() && !chbxRetirantTri.isSelected()) {
            view.viewLivraisonProduitAll();
        } else if (!chbxDateTri.isSelected() && chbxRetirantTri.isSelected()) {
            if (cbxRetirantTri.getSelectedItem().toString().equals("Tous les retirants")) {
                view.viewLivraisonProduitAll();
            } else {
                view.viewProduitLivraisonByNameReport(techDAOImpl.getTechnicienById(techIds.get(cbxRetirantTri.getSelectedIndex() - 1)));
            }
        } else if (chbxDateTri.isSelected() && !chbxRetirantTri.isSelected()) {
            if (periodValidator) {
                view.viewProduitLivraisonByPeriod(dtSince.getSelectedDate().getTime(), dtUntil.getSelectedDate().getTime());
            } else {
                JOptionPane.showMessageDialog(null, "Visualisez d'abord en cliquant sur OK.", "Attention", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (!periodValidator) {
                JOptionPane.showMessageDialog(null, "Visualisez d'abord en cliquant sur OK.", "Attention", JOptionPane.ERROR_MESSAGE);
            } else {
                if (retirantNameTri.equals("Tous les retirants")) {
                    view.viewProduitLivraisonByPeriod(dtSince.getSelectedDate().getTime(), dtUntil.getSelectedDate().getTime());
                } else {
                    view.viewProduitLivraisonByPeriodAndTech(techDAOImpl.getTechnicienById(techIds.get(cbxRetirantTri.getSelectedIndex() - 1)), dtSince.getSelectedDate().getTime(), dtUntil.getSelectedDate().getTime());
                }
            }
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void chbxDateTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxDateTriActionPerformed
        if (chbxDateTri.isSelected()) {
            dtSince.setEnabled(true);
            dtUntil.setEnabled(true);
            btnPrint.setEnabled(false);
        } else {
            dtSince.setEnabled(false);
            dtUntil.setEnabled(false);
            btnPrint.setEnabled(true);
        }
    }//GEN-LAST:event_chbxDateTriActionPerformed

    private void chbxRetirantTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxRetirantTriActionPerformed
        if (chbxRetirantTri.isSelected()) {
            cbxRetirantTri.setEnabled(true);
            cbxRetirantTri.setSelectedIndex(0);
            btnPrint.setEnabled(false);
        } else {
            cbxRetirantTri.setEnabled(false);
            btnPrint.setEnabled(true);
        }
    }//GEN-LAST:event_chbxRetirantTriActionPerformed

    private void btnOkTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkTriActionPerformed
        if (chbxDateTri.isSelected() && !chbxRetirantTri.isSelected()) {
            if (dtSince.getSelectedDate().after(dtUntil.getSelectedDate())) {
                JOptionPane.showMessageDialog(null, "Corrigez votre intervale des dates.", "Attention", JOptionPane.ERROR_MESSAGE);
            } else {
                periodValidator = true;
                List<ProduitDélivré> produits = getDaos().getProduitDélivréDAO().getProduitDélivréByPeriod(new java.sql.Date(dtSince.getSelectedDate().getTimeInMillis()), new java.sql.Date(dtUntil.getSelectedDate().getTimeInMillis()));
                listDisplayDelv(produits);
            }
        } else if (!chbxDateTri.isSelected() && chbxRetirantTri.isSelected()) {
            if (retirantNameTri.equals("Tous les retirants")) {
                List<ProduitDélivré> produits = getDaos().getProduitDélivréDAO().getAllProduitDélivré();
                listDisplayDelv(produits);
            } else {
                List<ProduitDélivré> produits = getDaos().getProduitDélivréDAO().getProduitDélivréByDélivreur(techDAOImpl.getTechnicienById(techIds.get(cbxRetirantTri.getSelectedIndex() - 1)).getId());
                listDisplayDelv(produits);
            }
        } else if (chbxDateTri.isSelected() && chbxRetirantTri.isSelected()) {
            if (dtSince.getSelectedDate().after(dtUntil.getSelectedDate())) {
                periodValidator = false;
                JOptionPane.showMessageDialog(null, "Corrigez votre intervale des dates.", "Attention", JOptionPane.ERROR_MESSAGE);
            } else if (retirantNameTri.equals("Tous les retirants")) {
                periodValidator = true;
                List<ProduitDélivré> produits = getDaos().getProduitDélivréDAO().getProduitDélivréByPeriod(new java.sql.Date(dtSince.getSelectedDate().getTimeInMillis()), new java.sql.Date(dtUntil.getSelectedDate().getTimeInMillis()));
                listDisplayDelv(produits);
            } else {
                periodValidator = true;
                List<ProduitDélivré> produits = getDaos().getProduitDélivréDAO().getProduitDélivréByPeriodAndDélivreur(techDAOImpl.getTechnicienById(techIds.get(cbxRetirantTri.getSelectedIndex() - 1)).getId(), new java.sql.Date(dtSince.getSelectedDate().getTimeInMillis()), new java.sql.Date(dtUntil.getSelectedDate().getTimeInMillis()));
                listDisplayDelv(produits);
            }
        }
        btnPrint.setEnabled(true);
    }//GEN-LAST:event_btnOkTriActionPerformed

    private void cbxRetirantTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRetirantTriActionPerformed
        retirantNameTri = cbxRetirantTri.getSelectedItem().toString();
    }//GEN-LAST:event_cbxRetirantTriActionPerformed

    public void listDisplay(List<MatièrePremière> products) {
        ids.clear();
        listLoad = false;
        listModel.clear();
        for (MatièrePremière prod : products) {
            if (!listModel.contains(getDaos().getProduitDAO().getProduitById(prod.getProductId()).getName())) {
                listModel.addElement(getDaos().getProduitDAO().getProduitById(prod.getProductId()).getName());
            }
            ids.add(prod.getId());
        }
        lstStock.setModel(listModel);
        listLoad = true;
    }

    public void listDisplayDelv(List<ProduitDélivré> prods) {
        Object[] columnName = new Object[tblHistorique.getColumnCount()];
        for (int i = 0; i < tblHistorique.getColumnCount(); i++) {
            columnName[i] = tblHistorique.getColumnName(i);
        }
        Object[][] rowData = new Object[prods.size()][tblHistorique.getColumnCount()];
        for (int i = 0; i < prods.size(); i++) {
            rowData[i][0] = techDAOImpl.getTechnicienById(prods.get(i).getDélivreur_id()).getLastName().concat(" " + techDAOImpl.getTechnicienById(prods.get(i).getDélivreur_id()).getFirstName());
            rowData[i][1] = getDaos().getProduitDAO().getProduitById(prods.get(i).getProduit_id()).getName();
            rowData[i][2] = prods.get(i).getQuantité();
            rowData[i][3] = prods.get(i).getLivraisonDate();
        }
        histTblModel = new DefaultTableModel(rowData, columnName);
        tblHistorique.setModel(histTblModel);
    }

    public void listDetails() {
        List<MatièrePremière> mats = new ArrayList<MatièrePremière>();
        String matName = lstStock.getSelectedValue().toString();
        mats = getDaos().getMatièrePremièreDAO().getMatièrePremièreByName(matName);
        fillIn(mats);
    }

    public void fillIn(List<MatièrePremière> products) {
        quantDispoTotal = 0.0;
        Object[] columnNames = new Object[5];
        for (int i = 0; i < 5; i++) {
            columnNames[i] = tblDetails.getColumnName(i);
        }
        Object[][] rowData = new Object[products.size()][5];
        for (int i = 0; i < products.size(); i++) {
            rowData[i][0] = getDaos().getProduitDAO().getProduitById(products.get(i).getProductId()).getName();
            rowData[i][1] = products.get(i).getOrigine();
            rowData[i][2] = products.get(i).getDateProduction();
            rowData[i][3] = products.get(i).getDateExpiration();
            rowData[i][4] = products.get(i).getQuantity();
            quantDispoTotal += products.get(i).getQuantity();
        }
        stockTblModel = new DefaultTableModel(rowData, columnNames);
        tblDetails.setModel(stockTblModel);
    }

    public void buttonEnabler(boolean enabler) {
        btnNvlLivraison.setEnabled(enabler);
        btnAnnuler.setEnabled(!enabler);
        btnLivrer.setEnabled(!enabler);
        btnAdd.setEnabled(!enabler);
        txtLivraison.setEnabled(!enabler);
    }

    private void tblTotalInit() {
        livraisonTtl = 0.0;
        rowNum = 0;
        columnTotal = new Object[tblTotal.getColumnCount()];
        for (int i = 0; i < tblTotal.getColumnCount(); i++) {
            columnTotal[i] = tblTotal.getColumnName(i);
        }
        totalData = new Object[0][tblTotal.getColumnCount()];
        totalTblModel = new DefaultTableModel(totalData, columnTotal);
        tblTotal.setModel(totalTblModel);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnLivrer;
    private javax.swing.JButton btnNvlLivraison;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOkTri;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox cbxAllerA;
    private javax.swing.JComboBox cbxRetirant;
    private javax.swing.JComboBox cbxRetirantTri;
    private javax.swing.JCheckBox chbxDateTri;
    private javax.swing.JCheckBox chbxRetirantTri;
    private datechooser.beans.DateChooserCombo dtSince;
    private datechooser.beans.DateChooserCombo dtUntil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JList lstStock;
    private javax.swing.JPanel pnlDateTri;
    private javax.swing.JPanel pnlRetirantTri;
    private javax.swing.JTable tblDetails;
    private javax.swing.JTable tblHistorique;
    private javax.swing.JTable tblTotal;
    private javax.swing.JTextField txtLivraison;
    // End of variables declaration//GEN-END:variables
}
