/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HistoriqueProductionUI.java
 *
 * Created on Feb 14, 2011, 6:01:23 PM
 */
package Aph.DAO.Impl.UI;

import Aph.Production;
import java.text.DateFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Medard
 */
public class HistoriqueProductionUI extends javax.swing.JFrame {

    private DAOS daos;
    private DateFormat ft;
    private String densitéTri;
    private boolean periodValidator;

    /** Creates new form HistoriqueProductionUI */
    public HistoriqueProductionUI() {
        initComponents();
        daos = new DAOS();
        ft = DateFormat.getDateInstance(DateFormat.LONG, Locale.FRANCE);
        dtSince.setDateFormat(ft);
        dtUntil.setDateFormat(ft);
        dtSince.setEnabled(false);
        dtUntil.setEnabled(false);
        cbxDensité.setEnabled(false);
        tblHistorique.setEnabled(false);
        for (int i = 0; i < daos.getDensitéDAO().getAllDensité().size(); i++) {
            cbxDensité.addItem(daos.getDensitéDAO().getAllDensité().get(i).getName());
        }
    }

    public DAOS getDaos() {
        return daos;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorique = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dtUntil = new datechooser.beans.DateChooserCombo();
        dtSince = new datechooser.beans.DateChooserCombo();
        jPanel2 = new javax.swing.JPanel();
        cbxDensité = new javax.swing.JComboBox();
        chbxDensités = new javax.swing.JCheckBox();
        chbxDates = new javax.swing.JCheckBox();
        btnOK = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblHistorique.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Densité", "Durée(Minutes)", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHistorique.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblHistorique);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tri rafiné par date et/ou densité", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtSince, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(dtUntil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dtSince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtUntil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cbxDensité.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Toutes les densités" }));
        cbxDensité.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDensitéActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxDensité, 0, 152, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxDensité, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        chbxDensités.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxDensitésActionPerformed(evt);
            }
        });

        chbxDates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxDatesActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chbxDates)
                    .addComponent(chbxDensités))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addComponent(btnOK))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbxDates))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(chbxDensités)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnOK)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imprimer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        btnPrint.setText("Imprimer");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrint)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrint)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        List<Production> productions = getDaos().getProductionDAO().getAllProduction();
        listDisplay(productions);
    }//GEN-LAST:event_formWindowOpened

    private void cbxDensitéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDensitéActionPerformed
        densitéTri = cbxDensité.getSelectedItem().toString();
    }//GEN-LAST:event_cbxDensitéActionPerformed

    private void chbxDatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxDatesActionPerformed
        if (chbxDates.isSelected()) {
            dtSince.setEnabled(true);
            dtUntil.setEnabled(true);
            btnPrint.setEnabled(false);
        } else {
            dtSince.setEnabled(false);
            dtUntil.setEnabled(false);
            btnPrint.setEnabled(true);
        }
    }//GEN-LAST:event_chbxDatesActionPerformed

    private void chbxDensitésActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxDensitésActionPerformed
        if (chbxDensités.isSelected()) {
            cbxDensité.setEnabled(true);
            cbxDensité.setSelectedIndex(0);
            btnPrint.setEnabled(false);
        } else {
            cbxDensité.setEnabled(false);
            btnPrint.setEnabled(true);
        }
    }//GEN-LAST:event_chbxDensitésActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (chbxDates.isSelected() && !chbxDensités.isSelected()) {
            if (dtSince.getSelectedDate().after(dtUntil.getSelectedDate())) {
                JOptionPane.showMessageDialog(null, "Corrigez votre intervale des dates.", "Attention", JOptionPane.ERROR_MESSAGE);
            } else {
                periodValidator = true;
                List<Production> prods = getDaos().getProductionDAO().getProductionByTimeInterval(new java.sql.Date(dtSince.getSelectedDate().getTimeInMillis()), new java.sql.Date(dtUntil.getSelectedDate().getTimeInMillis()));
                listDisplay(prods);
            }
        } else if (!chbxDates.isSelected() && chbxDensités.isSelected()) {
            if (densitéTri.equals("Toutes les densités")) {
                List<Production> prods = getDaos().getProductionDAO().getAllProduction();
                listDisplay(prods);
            } else {
                List<Production> prods = getDaos().getProductionDAO().getProductionByDensity(getDaos().getDensitéDAO().getDensitéByName(densitéTri).getId());
                listDisplay(prods);
            }
        } else if (chbxDates.isSelected() && chbxDensités.isSelected()) {
            if (dtSince.getSelectedDate().after(dtUntil.getSelectedDate())) {
                periodValidator = false;
                JOptionPane.showMessageDialog(null, "Corrigez votre intervale des dates.", "Attention", JOptionPane.ERROR_MESSAGE);
            } else if (densitéTri.equals("Toutes les densités")) {
                periodValidator = true;
                List<Production> prods = getDaos().getProductionDAO().getProductionByTimeInterval(new java.sql.Date(dtSince.getSelectedDate().getTimeInMillis()), new java.sql.Date(dtUntil.getSelectedDate().getTimeInMillis()));
                listDisplay(prods);
            } else {
                periodValidator = true;
                List<Production> prods = getDaos().getProductionDAO().getProductionByPeriodAndDensity(new java.sql.Date(dtSince.getSelectedDate().getTimeInMillis()), new java.sql.Date(dtUntil.getSelectedDate().getTimeInMillis()), getDaos().getDensitéDAO().getDensitéByName(densitéTri).getId());
                listDisplay(prods);
            }
        }
        btnPrint.setEnabled(true);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        Reports view = new Reports();
        if (!chbxDates.isSelected() && !chbxDensités.isSelected()) {
            view.viewAllProduction();
        } else if (!chbxDates.isSelected() && chbxDensités.isSelected()) {
            if (cbxDensité.getSelectedItem().toString().equals("Toutes les densités")) {
                view.viewAllProduction();
            } else {
                view.viewProductionByDensité(getDaos().getDensitéDAO().getDensitéByName(densitéTri));
            }
        } else if (chbxDates.isSelected() && !chbxDensités.isSelected()) {
            if (periodValidator) {
                view.viewProductionByPeriod(dtSince.getSelectedDate().getTime(), dtUntil.getSelectedDate().getTime());
            } else {
                JOptionPane.showMessageDialog(null, "Visualisez d'abord en cliquant sur OK.", "Attention", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            if (!periodValidator) {
                JOptionPane.showMessageDialog(null, "Visualisez d'abord en cliquant sur OK.", "Attention", JOptionPane.ERROR_MESSAGE);
            } else {
                if (densitéTri.equals("Toutes les densités")) {
                    view.viewProductionByPeriod(dtSince.getSelectedDate().getTime(), dtUntil.getSelectedDate().getTime());
                } else {
                    view.viewProductionByDensityAndPeriod(dtSince.getSelectedDate().getTime(), dtUntil.getSelectedDate().getTime(), getDaos().getDensitéDAO().getDensitéByName(densitéTri));
                }
            }
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void listDisplay(List<Production> productions) {
        Object[][] rowData = new Object[productions.size()][tblHistorique.getColumnCount()];
        Object[] columns = new Object[tblHistorique.getColumnCount()];
        for (int i = 0; i < tblHistorique.getColumnCount(); i++) {
            columns[i] = tblHistorique.getColumnName(i);
        }
        for (int i = 0; i < productions.size(); i++) {
            rowData[i][0] = getDaos().getDensitéDAO().getDensitéById(productions.get(i).getDensitéId()).getName();
            rowData[i][1] = productions.get(i).getMinutes();
            rowData[i][2] = productions.get(i).getDate();
        }
        tblHistorique.setModel(new DefaultTableModel(rowData, columns));
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox cbxDensité;
    private javax.swing.JCheckBox chbxDates;
    private javax.swing.JCheckBox chbxDensités;
    private datechooser.beans.DateChooserCombo dtSince;
    private datechooser.beans.DateChooserCombo dtUntil;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHistorique;
    // End of variables declaration//GEN-END:variables
}
