/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProductionUI.java
 *
 * Created on Jan 13, 2011, 12:26:58 AM
 */
package Aph.DAO.Impl.UI;

import Aph.Citerne;
import Aph.Densité;
import Aph.Production;
import Aph.ProduitSemiFini;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Medard
 */
public class ProductionUI extends javax.swing.JFrame {

    private DAOS daos;
    private Densité densité;
    private Object[][] densitéCons;
    private String selectedDensity;
    private HistoriqueProductionUI historiqueUI;

    /** Creates new form ProductionUI */
    public ProductionUI() {
        initComponents();
        daos = new DAOS();
        densité = new Densité();
        List<Densité> densités = daos.getDensitéDAO().getAllDensité();
        for (Densité dens : densités) {
            cbxDensité.addItem(dens.getName());
        }
        historiqueUI = new HistoriqueProductionUI();
        historiqueUI.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public DAOS getDaos() {
        return daos;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnVérifier = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        cbxDensité = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDurée = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnLancer = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Colonna MT", 3, 24));
        jLabel1.setText("Productions");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nouvelle production", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        btnVérifier.setText("Vérifier");
        btnVérifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVérifierActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");

        cbxDensité.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choisir" }));
        cbxDensité.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDensitéActionPerformed(evt);
            }
        });

        jLabel4.setText("min.");

        jLabel2.setText("Densité:");

        jLabel3.setText("Durée(min):");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDurée)
                    .addComponent(cbxDensité, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(btnAnnuler))
                    .addComponent(btnVérifier, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnnuler, btnVérifier});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxDensité, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVérifier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDurée, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnAnnuler))
                .addContainerGap())
        );

        btnLancer.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        btnLancer.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnLancer.setText("Lancer la production");
        btnLancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancerActionPerformed(evt);
            }
        });

        jButton1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 10));
        jButton1.setText("Historique");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(btnLancer)
                .addContainerGap(131, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(311, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLancer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        buttonEnabler(true);
    }//GEN-LAST:event_formWindowOpened

    private void btnVérifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVérifierActionPerformed
        int minutes = 0;
        String insuffisant = "Les produits suivants sont insuffisants:\n";
        try {
            minutes = Integer.parseInt(txtDurée.getText());
            int approve = 0;
            if (selectedDensity.equals("Choisir")) {
                JOptionPane.showMessageDialog(null, "Précisez la densité que vous voulez produir.", "Attention", JOptionPane.ERROR_MESSAGE);
            } else if (txtDurée.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Spécifiez la durée en minutes.", "Attention", JOptionPane.ERROR_MESSAGE);
            } else {
                densité = getDaos().getDensitéDAO().getDensitéByName(selectedDensity);
                densitéCons = new Object[densité.getConsRowNum()][2];
                densitéCons = densité.getConsommation();
                for (int i = 0; i < densité.getConsRowNum(); i++) {
                    if (Double.parseDouble(densitéCons[i][1].toString()) != 0) {
                        double availableProd = getDaos().getCiterneDAO().getTotalSameContentInCiternesByProductId(getDaos().getTotalProduitDélivréDAO().getTotalProduitByProduitId(getDaos().getProduitDAO().getProduitByName(densitéCons[i][0].toString()).getId()).getId());
                        if (availableProd < (Double.parseDouble(densitéCons[i][1].toString()) * minutes)) {
                            insuffisant += "  " + densitéCons[i][0].toString() + "\n";
                            JOptionPane.showMessageDialog(null, "Av: "+availableProd+"; Req:"+Double.parseDouble(densitéCons[i][1].toString()) * minutes);
                        } else {
                            ++approve;
                        }
                    }
                }
                if (approve == densité.getConsRowNum()) {
                    JOptionPane.showMessageDialog(null, "Vous pouvez lancer la production.", "Feu vert", JOptionPane.INFORMATION_MESSAGE);
                    buttonEnabler(false);
                } else {
                    JOptionPane.showMessageDialog(null, insuffisant, "Attention", JOptionPane.ERROR_MESSAGE);
                    buttonEnabler(true);
                }
            }
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Précisez la durée de production en chiffres(Minutes).", "Attention", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVérifierActionPerformed

    private void cbxDensitéActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDensitéActionPerformed
        selectedDensity = cbxDensité.getSelectedItem().toString();
    }//GEN-LAST:event_cbxDensitéActionPerformed

    private void btnLancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancerActionPerformed
        Production production = new Production(getDaos().getDensitéDAO().getDensitéByName(cbxDensité.getSelectedItem().toString()).getId(), Integer.parseInt(txtDurée.getText()));
        Production returned = getDaos().getProductionDAO().createProduction(production);
        if (returned != null) {
            JOptionPane.showMessageDialog(null, "La production efféctuée.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            cascade(returned);
        } else {
            JOptionPane.showMessageDialog(null, "La production a échoué.", "Erreur de production", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLancerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        historiqueUI.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void buttonEnabler(boolean enabler) {
        btnVérifier.setEnabled(enabler);
        btnAnnuler.setEnabled(!enabler);
        btnLancer.setEnabled(!enabler);
    }

    private void cascade(Production prod) {
        Densité dens = getDaos().getDensitéDAO().getDensitéById(prod.getDensitéId());
        Object[][] cons = dens.getConsommation();

        for (int i = 0; i < dens.getConsRowNum(); i++) {
            List<Citerne> cits = getDaos().getCiterneDAO().getCiterneByContent(getDaos().getProduitDAO().getProduitByName(cons[i][0].toString()).getId());
            double totalConsPerProd = Double.parseDouble(cons[i][1].toString()) * prod.getMinutes();
            for (Citerne cit : cits) {
                if (cit.getQuantité() < totalConsPerProd) {
                    totalConsPerProd -= cit.getQuantité();
                    cit.setQuantité(0.0);
                    getDaos().getCiterneDAO().updateCiterne(cit);
                } else {
                    cit.setQuantité(cit.getQuantité() - totalConsPerProd);
                    getDaos().getCiterneDAO().updateCiterne(cit);
                }
            }
        }
        ProduitSemiFini block = new ProduitSemiFini(dens.getName().concat("Block"), dens.getId());
        getDaos().getProduitSemiFiniDAO().createProduitSemiFini(block);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnLancer;
    private javax.swing.JButton btnVérifier;
    private javax.swing.JComboBox cbxDensité;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDurée;
    // End of variables declaration//GEN-END:variables
}
