package Aph.DAO.Impl.UI;

import Aph.ProduitSemiFini;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;


/*
 * ProduitSemiFiniUI.java
 *
 * Created on Dec 19, 2010, 4:05:10 PM
 */
/**
 *
 * @author Medard
 */
public class ProduitSemiFiniUI extends javax.swing.JFrame {

    private DAOS daos;
    private int currentRow;
    private List<ProduitSemiFini> products;
    private ArrayList<Integer> ids = new ArrayList<Integer>();
    private DefaultListModel listModel = new DefaultListModel();
    private ProduitSemiFini block = new ProduitSemiFini();
    private boolean listLoad;
    private String critère;
    private Gestion_blocks getsBlock;

    /** Creates new form ProduitSemiFiniUI */
    public ProduitSemiFiniUI() {
        initComponents();
        daos = new DAOS();
        this.setTitle("Produits Semi-finis");
    }

    public DAOS getDaos() {
        return daos;
    }

    public Gestion_blocks getGetsBlock() {
        return getsBlock;
    }

    public void setGetsBlock(Gestion_blocks getsBlock) {
        this.getsBlock = getsBlock;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstProduits = new javax.swing.JList();
        txtNom = new javax.swing.JTextField();
        txtPoids = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnModifier = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();
        btnEffacer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbxSearch = new javax.swing.JComboBox();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        MaskFormatter mf = null;
        try{
            mf = new MaskFormatter("###×###×##");
            mf.setPlaceholderCharacter('_');
        }catch(ParseException p){
            p.printStackTrace();
        }
        ftxtDimension = new javax.swing.JFormattedTextField(mf);
        txtSections = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblDensité = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lstProduits.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstProduitsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstProduits);

        jLabel1.setFont(new java.awt.Font("Colonna MT", 3, 24)); // NOI18N
        jLabel1.setText("Blocks");

        jLabel2.setText("Nom");

        jLabel3.setText("Poids");

        jLabel4.setText("Dimension");

        jLabel5.setText("Densité");

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        btnPrevious.setText("<");

        btnNext.setText(">");

        jLabel6.setText("Rechecher");

        cbxSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionner critère", "Nom", "Densité" }));
        cbxSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSearchActionPerformed(evt);
            }
        });

        btnSearch.setText("Chercher");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel9.setText("Nombre de séctions");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btnModifier)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEnregistrer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEffacer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAnnuler))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(lblDensité, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNom, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPoids, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ftxtDimension, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(txtSections, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(btnPrevious)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(btnNext)
                                                    .addGap(6, 6, 6))))))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)))
                .addContainerGap())
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAnnuler, btnEffacer, btnEnregistrer, btnModifier});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftxtDimension, lblDensité, txtNom, txtPoids});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnPrevious)
                            .addComponent(btnNext))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPoids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ftxtDimension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSections, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDensité))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModifier)
                            .addComponent(btnEnregistrer)
                            .addComponent(btnEffacer)
                            .addComponent(btnAnnuler)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ftxtDimension, lblDensité, txtNom, txtPoids});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        List<ProduitSemiFini> allProducts = getDaos().getProduitSemiFiniDAO().getAllProduitSemiFini();
        listDisplay(allProducts);
        listLoad = false;
        lstProduits.setSelectedIndex(0);
        listDetails();
        listLoad = true;
        lstProduits.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        buttonEnabler(false);
        currentRow = lstProduits.getSelectedIndex();
        txtNom.requestFocus();
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        ProduitSemiFini produit = new ProduitSemiFini();
        listLoad = false;
        produit = getDaos().getProduitSemiFiniDAO().getProduitSemiFiniById(ids.get(lstProduits.getSelectedIndex()));
        produit.setName(txtNom.getText());
        produit.setPoids(Double.parseDouble(txtPoids.getText()));
        produit.setDimension(ftxtDimension.getText());
        produit.setNbrSections(Integer.parseInt(txtSections.getText()));
        boolean updated = getDaos().getProduitSemiFiniDAO().updateProduitSemiFini(produit);
        if (updated) {
            JOptionPane.showMessageDialog(null, "Modifications efféctuées.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Opération échouée.", "Attention", JOptionPane.ERROR_MESSAGE);
        }
        listDisplay(getDaos().getProduitSemiFiniDAO().getAllProduitSemiFini());
        listLoad = true;
        lstProduits.setSelectedValue(getDaos().getProduitSemiFiniDAO().getProduitSemiFiniById(produit.getId()).getName(), true);
        lstProduits.requestFocus();
        buttonEnabler(true);
        this.getGetsBlock().refreshForm();
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Voulez-vous éffacer le produit " + lstProduits.getSelectedValue().toString(), "Confirmez", JOptionPane.YES_NO_CANCEL_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            boolean deleted = getDaos().getProduitSemiFiniDAO().deleteproduitSemiFini(ids.get(lstProduits.getSelectedIndex()));
            if (deleted) {
                JOptionPane.showMessageDialog(null, "Suppression efféctuée", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        listLoad = false;
        listDisplay(getDaos().getProduitSemiFiniDAO().getAllProduitSemiFini());
        lstProduits.setSelectedIndex(0);
        listDetails();
        listLoad = true;
        lstProduits.requestFocus();
    }//GEN-LAST:event_btnEffacerActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        buttonEnabler(true);
        lstProduits.setSelectedIndex(currentRow);
        lstProduits.requestFocus();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void lstProduitsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProduitsValueChanged
        if (listLoad == true) {
            listDetails();
        }
    }//GEN-LAST:event_lstProduitsValueChanged

    private void cbxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSearchActionPerformed
        critère = cbxSearch.getSelectedItem().toString();
    }//GEN-LAST:event_cbxSearchActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        List<ProduitSemiFini> produits = new ArrayList<ProduitSemiFini>();
        if (critère.equals("Sélectionner critère")) {
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner le critère de recherche.", "Attention", JOptionPane.ERROR_MESSAGE);
        } else {
            if (txtSearch.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Précisez le critère de recherche.", "Attention", JOptionPane.ERROR_MESSAGE);
            } else {
                if (critère.equals("Nom")) {
                    produits = getDaos().getProduitSemiFiniDAO().getProduitSemiFiniByName(txtSearch.getText());
                } else if (critère.equals("Densité")) {
                    produits = getDaos().getProduitSemiFiniDAO().getProduitSemiFiniByDensity(getDaos().getDensitéDAO().getDensitéByName(txtSearch.getText()).getId());
                }
                if (produits.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Aucun produit trouvé sous le nom de " + txtSearch.getText(), "Alerte", JOptionPane.ERROR_MESSAGE);
                } else {
                    listLoad = false;
                    listDisplay(produits);
                    lstProduits.setSelectedIndex(0);
                    listDetails();
                    listLoad = true;
                }
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    public void buttonEnabler(boolean enabler) {
        btnEnregistrer.setEnabled(!enabler);
        btnAnnuler.setEnabled(!enabler);
        btnModifier.setEnabled(enabler);
        btnEffacer.setEnabled(enabler);
        btnPrevious.setEnabled(enabler);
        btnNext.setEnabled(enabler);
    }

    private void listDisplay(List<ProduitSemiFini> blocks) {
        ids.clear();
        listModel.clear();
        for (ProduitSemiFini prod : blocks) {
            listModel.addElement(prod.getName());
            ids.add(prod.getId());
        }
        lstProduits.setModel(listModel);
    }

    public void listDetails() {
        block = new ProduitSemiFini();
        int blockIndex = lstProduits.getSelectedIndex();
        int blockId = ids.get(blockIndex);
        block = getDaos().getProduitSemiFiniDAO().getProduitSemiFiniById(blockId);
        fillIn(block);
    }

    public void fillIn(ProduitSemiFini prod) {
        txtNom.setText(prod.getName());
        txtPoids.setText(Double.toString(prod.getPoids()));
        ftxtDimension.setText(prod.getDimension().toString());
        lblDensité.setText((getDaos().getDensitéDAO().getDensitéById(prod.getDensityId()).getName()));
        txtSections.setText(Integer.toString(prod.getNbrSections()));
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEffacer;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cbxSearch;
    private javax.swing.JFormattedTextField ftxtDimension;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDensité;
    private javax.swing.JList lstProduits;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPoids;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSections;
    // End of variables declaration//GEN-END:variables
}
