/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TechnicienProdUI.java
 *
 * Created on Jan 31, 2011, 9:42:31 AM
 */
package Aph.DAO.Impl.UI;

import Aph.DAO.Impl.TechnicienProduitDAOImpl;
import Aph.Technicien;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Medard
 */
public class TechnicienProdUI extends javax.swing.JFrame {

    private TechnicienProduitDAOImpl techDAOImpl;
    private boolean saveOrUpdate;
    private DefaultListModel listmodel = new DefaultListModel();
    private Technicien technicien;
    private boolean listLoad;
    private String searchCriterion;
    private int currentRow;
    private List<Integer> ids = new ArrayList<Integer>();

    /** Creates new form TechnicienProdkUI */
    public TechnicienProdUI() {
        initComponents();
        techDAOImpl = new TechnicienProduitDAOImpl();
        lstTechniciens.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        cbxSearch.getComponent(0).setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstTechniciens = new javax.swing.JList();
        txtNom = new javax.swing.JTextField();
        txtPrénom = new javax.swing.JTextField();
        txtNumTel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        btnEffacer = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cbxSearch = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnChercher = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lstTechniciens.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTechniciens.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTechniciensValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstTechniciens);

        jLabel1.setText("Nom");

        jLabel2.setText("Prénom");

        jLabel3.setText("Numéro de tel");

        jLabel4.setFont(new java.awt.Font("Colonna MT", 3, 24));
        jLabel4.setText("Techniciens");

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        btnPrevious.setText("<");

        btnNext.setText(">");

        cbxSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionner critère", "Nom", "Prénom", "Numéro de tel" }));
        cbxSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSearchActionPerformed(evt);
            }
        });

        jLabel5.setText("Rechercher");

        btnChercher.setText("Chercher");
        btnChercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChercherActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrénom)
                            .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(txtNumTel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnregistrer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEffacer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnnuler)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChercher)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAjouter, btnAnnuler, btnEffacer, btnEnregistrer, btnModifier});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btnPrevious)
                            .addComponent(btnNext))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAjouter)
                            .addComponent(btnModifier)
                            .addComponent(btnEnregistrer)
                            .addComponent(btnEffacer)
                            .addComponent(btnAnnuler))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChercher))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        txtNom.setText("");
        txtPrénom.setText("");
        txtNumTel.setText("");
        buttonEnabler(false);
        saveOrUpdate = true;
        txtNom.requestFocus();
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        listLoad = false;
        Technicien tech;
        if (saveOrUpdate) {
            tech = new Technicien(txtNom.getText(), txtPrénom.getText(), txtNumTel.getText());
            techDAOImpl.createTechnicien(tech);
            JOptionPane.showMessageDialog(null, "Enregistrement effectué", "Enregistrement", JOptionPane.INFORMATION_MESSAGE);
        } else {
            tech = techDAOImpl.getTechnicienById(technicien.getId());
            tech.setLastName(txtNom.getText());
            tech.setFirstName(txtPrénom.getText());
            tech.setNumTel(txtNumTel.getText());
            boolean updated = techDAOImpl.updateTechnicien(tech);
            if (updated) {
                JOptionPane.showMessageDialog(null, "Modification effectuée", "Modification", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        listDisplay(techDAOImpl.getAllTechniciens());
        listLoad = true;
        lstTechniciens.setSelectedValue(tech.getLastName() + " " + tech.getFirstName(), true);
        lstTechniciens.requestFocus();
        buttonEnabler(true);
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer le technicien: " + txtNom.getText(), "Confirmer", JOptionPane.YES_NO_CANCEL_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            boolean deleted = techDAOImpl.deleteTechnicien(ids.get(lstTechniciens.getSelectedIndex()));
            if (deleted) {
                JOptionPane.showMessageDialog(null, "Opération effectuée", "Suppression", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        listLoad = false;
        listDisplay(techDAOImpl.getAllTechniciens());
        lstTechniciens.setSelectedIndex(0);
        listDetails();
        listLoad = true;
        lstTechniciens.requestFocus();
        buttonEnabler(true);
    }//GEN-LAST:event_btnEffacerActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        buttonEnabler(true);
        lstTechniciens.setSelectedIndex(currentRow);
        lstTechniciens.requestFocus();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        buttonEnabler(false);
        saveOrUpdate = false;
        currentRow = lstTechniciens.getSelectedIndex();
        txtNom.requestFocus();
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChercherActionPerformed
        listLoad = false;
        List<Technicien> techn = new ArrayList<Technicien>();
        if (!searchCriterion.equals("Sélectionner critère")) {
            if (searchCriterion.equals("Nom")) {
                techn = techDAOImpl.getTechnicienByLastName(txtSearch.getText());
            } else if (searchCriterion.equals("Prénom")) {
                techn = techDAOImpl.getTechnicienByFirstName(txtSearch.getText());
            } else if (searchCriterion.equals("Numéro de téléphone")) {
                techn.add(techDAOImpl.getTechnicienByPhoneNum(txtSearch.getText()));
            }
            if (techn.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Aucun technicien trouvé.", "Attention", JOptionPane.ERROR_MESSAGE);
            } else {
                listDisplay(techn);
                lstTechniciens.setSelectedIndex(0);
                listDetails();
                listLoad = true;
                lstTechniciens.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Précisez le critère de recherche.", "Attention", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnChercherActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listDisplay(techDAOImpl.getAllTechniciens());
        listLoad = true;
        lstTechniciens.setSelectedIndex(0);
        buttonEnabler(true);
        listDetails();
    }//GEN-LAST:event_formWindowOpened

    private void cbxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSearchActionPerformed
        searchCriterion = cbxSearch.getSelectedItem().toString();
    }//GEN-LAST:event_cbxSearchActionPerformed

    private void lstTechniciensValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTechniciensValueChanged
        if (listLoad == true) {
            listDetails();
        }
    }//GEN-LAST:event_lstTechniciensValueChanged
    public void fillIn(Technicien tech) {
        txtNom.setText(tech.getLastName());
        txtPrénom.setText(tech.getFirstName());
        txtNumTel.setText(tech.getNumTel());
    }

    public void listDisplay(List<Technicien> techns) {
        int i = 1;
        ids.clear();
        listmodel.clear();
        for (Technicien techn : techns) {
            listmodel.addElement(i + "." + techn.getLastName().concat(" " + techn.getFirstName()));
            ids.add(techn.getId());
            ++i;
        }
        lstTechniciens.setModel(listmodel);
    }

    public void listDetails() {
        technicien = new Technicien();
        int techIndex = lstTechniciens.getSelectedIndex();
        int techId = ids.get(techIndex);
        technicien = techDAOImpl.getTechnicienById(techId);
        fillIn(technicien);
    }

    public void buttonEnabler(boolean enabler) {
        btnEnregistrer.setEnabled(!enabler);
        btnAnnuler.setEnabled(!enabler);
        btnAjouter.setEnabled(enabler);
        btnModifier.setEnabled(enabler);
        btnEffacer.setEnabled(enabler);
        btnChercher.setEnabled(enabler);
        btnPrevious.setEnabled(enabler);
        btnNext.setEnabled(enabler);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnChercher;
    private javax.swing.JButton btnEffacer;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JComboBox cbxSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList lstTechniciens;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumTel;
    private javax.swing.JTextField txtPrénom;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
