package Aph.DAO.Impl.UI;

import Aph.Technicien;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/*
 * TechnicienBlockUI.java
 *
 * Created on Dec 19, 2010, 4:20:53 PM
 */
/**
 *
 * @author Medard
 */
public class TechnicienBlockUI extends javax.swing.JFrame {

    private DAOS daos;
    private boolean saveOrUpdate;
    private DefaultListModel listmodel = new DefaultListModel();
    private List<Technicien> techniciens = new ArrayList<Technicien>();
    private Technicien technicien;
    private boolean listLoad;
    private String searchCriterion;
    private int currentRow;
    private List<Integer> ids = new ArrayList<Integer>();

    /** Creates new form TechnicienBlockUI */
    public TechnicienBlockUI() {
        initComponents();
        daos = new DAOS();
        lstTechniciens.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        cbxSearch.getComponent(0).setEnabled(false);
    }

    public DAOS getDaos() {
        return daos;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstTechniciens = new javax.swing.JList();
        txtNom = new javax.swing.JTextField();
        txtPrénom = new javax.swing.JTextField();
        txtNumTel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();
        btnEffacer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        cbxSearch = new javax.swing.JComboBox();
        txtSearch = new javax.swing.JTextField();
        btnChercher = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lstTechniciens.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTechniciens.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstTechniciensValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstTechniciens);

        jLabel1.setFont(new java.awt.Font("Colonna MT", 3, 24));
        jLabel1.setText("Technicien");

        jLabel2.setText("Nom");

        jLabel3.setText("Prénom");

        jLabel4.setText("Numéro de tel.");

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        jLabel5.setText("Rechercher");

        cbxSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sélectionner critère ", "Nom", "Prénom", "Numéro de téléphone" }));
        cbxSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSearchActionPerformed(evt);
            }
        });

        btnChercher.setText("Chercher");
        btnChercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChercherActionPerformed(evt);
            }
        });

        btnPrevious.setText("<");

        btnNext.setText(">");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChercher)
                        .addContainerGap(193, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(btnAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnModifier, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEnregistrer, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEffacer, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAnnuler, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNom, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addComponent(txtPrénom)
                                            .addComponent(txtNumTel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPrevious)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNext)))))
                        .addContainerGap())
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnPrevious)
                            .addComponent(btnNext))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModifier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEnregistrer)
                            .addComponent(btnEffacer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnnuler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChercher))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        listLoad = false;
        Technicien tech;
        if (saveOrUpdate) {
            tech = new Technicien(txtNom.getText(), txtPrénom.getText(), txtNumTel.getText());
            getDaos().getTechnicienDAO().createTechnicien(tech);
            JOptionPane.showMessageDialog(null, "Enregistrement effectué", "Enregistrement", JOptionPane.INFORMATION_MESSAGE);
        } else {
            tech = getDaos().getTechnicienDAO().getTechnicienById(technicien.getId());
            tech.setLastName(txtNom.getText());
            tech.setFirstName(txtPrénom.getText());
            tech.setNumTel(txtNumTel.getText());
            boolean updated = getDaos().getTechnicienDAO().updateTechnicien(tech);
            if (updated) {
                JOptionPane.showMessageDialog(null, "Modification effectuée", "Modification", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        listDisplay(getDaos().getTechnicienDAO().getAllTechniciens());
        listLoad = true;
        lstTechniciens.setSelectedValue(tech.getLastName() + " " + tech.getFirstName(), true);
        lstTechniciens.requestFocus();
        buttonEnabler(true);
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        txtNom.setText("");
        txtPrénom.setText("");
        txtNumTel.setText("");
        buttonEnabler(false);
        saveOrUpdate = true;
        txtNom.requestFocus();
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listDisplay(getDaos().getTechnicienDAO().getAllTechniciens());
        listLoad = false;
        lstTechniciens.setSelectedIndex(0);
        buttonEnabler(true);
        listDetails();
        listLoad = true;
    }//GEN-LAST:event_formWindowOpened

    private void lstTechniciensValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstTechniciensValueChanged
        if (listLoad == true) {
            listDetails();
        }
    }//GEN-LAST:event_lstTechniciensValueChanged

    private void cbxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSearchActionPerformed
        searchCriterion = cbxSearch.getSelectedItem().toString();
    }//GEN-LAST:event_cbxSearchActionPerformed

    private void btnChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChercherActionPerformed
        listLoad = false;
        if (searchCriterion.equals("Nom")) {
            List<Technicien> techn = getDaos().getTechnicienDAO().getTechnicienByLastName(txtSearch.getText());
            listDisplay(techn);
        } else if (searchCriterion.equals("Prénom")) {
            List<Technicien> techn = getDaos().getTechnicienDAO().getTechnicienByFirstName(txtSearch.getText());
            listDisplay(techn);
        } else if (searchCriterion.equals("Numéro de téléphone")) {
            List<Technicien> techn = new ArrayList<Technicien>();
            techn.add(getDaos().getTechnicienDAO().getTechnicienByPhoneNum(txtSearch.getText()));
            listDisplay(techn);
        }
        lstTechniciens.setSelectedIndex(0);
        listDetails();
        listLoad = true;
        lstTechniciens.requestFocus();
    }//GEN-LAST:event_btnChercherActionPerformed

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer le technicien: " + txtNom.getText(), "Confirmer", JOptionPane.YES_NO_CANCEL_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            boolean deleted = getDaos().getTechnicienDAO().deleteTechnicien(ids.get(lstTechniciens.getSelectedIndex()));
            if (deleted) {
                JOptionPane.showMessageDialog(null, "Opération effectuée", "Suppression", JOptionPane.INFORMATION_MESSAGE);
                listLoad = false;
                listDisplay(getDaos().getTechnicienDAO().getAllTechniciens());
                lstTechniciens.setSelectedIndex(0);
                listDetails();
                listLoad = true;
                lstTechniciens.requestFocus();
                buttonEnabler(true);
            }
        }
    }//GEN-LAST:event_btnEffacerActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        buttonEnabler(true);
        lstTechniciens.setSelectedIndex(currentRow);
        lstTechniciens.requestFocus();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        buttonEnabler(false);
        saveOrUpdate = false;
        currentRow = lstTechniciens.getSelectedIndex();
        txtNom.requestFocus();
    }//GEN-LAST:event_btnModifierActionPerformed
    public void fillIn(Technicien tech) {
        txtNom.setText(tech.getLastName());
        txtPrénom.setText(tech.getFirstName());
        txtNumTel.setText(tech.getNumTel());
    }

    public void listDisplay(List<Technicien> techns) {
        int i = 1;
        ids.clear();
        listmodel.clear();
        for (Technicien techn : techns) {
            listmodel.addElement(i + ". " + techn.getLastName().concat(" " + techn.getFirstName()));
            ids.add(techn.getId());
            ++i;
        }
        lstTechniciens.setModel(listmodel);
    }

    public void listDetails() {
        technicien = new Technicien();
        int techIndex = lstTechniciens.getSelectedIndex();
        int techId = ids.get(techIndex);
        technicien = getDaos().getTechnicienDAO().getTechnicienById(techId);
        fillIn(technicien);
    }

    public void buttonEnabler(boolean enabler) {
        btnEnregistrer.setEnabled(!enabler);
        btnAnnuler.setEnabled(!enabler);
        btnAjouter.setEnabled(enabler);
        btnModifier.setEnabled(enabler);
        btnEffacer.setEnabled(enabler);
        btnChercher.setEnabled(enabler);
        btnPrevious.setEnabled(enabler);
        btnNext.setEnabled(enabler);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnChercher;
    private javax.swing.JButton btnEffacer;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JComboBox cbxSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList lstTechniciens;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumTel;
    private javax.swing.JTextField txtPrénom;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
