/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UsersUI.java
 *
 * Created on Dec 24, 2010, 12:13:05 PM
 */
package Aph.DAO.Impl.UI;

import Aph.User;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Medard
 */
public class UsersUI extends javax.swing.JFrame {

    private DAOS daos;
    private boolean saveOrUpdate, listLoad;
    private DefaultListModel listmodel = new DefaultListModel();
    private String grade;
    private User user;
    private int selectedItemIndex;
    private List<User> users;
    private int currentRow;

    /** Creates new form UsersUI */
    public UsersUI() {
        initComponents();
        daos = new DAOS();
        lstUsers.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        cbxGrade.setEditable(false);
        this.setTitle("Utilisateurs");
    }

    public DAOS getDaos() {
        return daos;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsers = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        txtPrénom = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        cbxGrade = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();
        btnEffacer = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnDéconnecter = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lblGrade = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lstUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstUsers);

        jLabel1.setFont(new java.awt.Font("Colonna MT", 3, 24));
        jLabel1.setText("Utilisateurs ");

        cbxGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administateur", "Gestionnaire-Citernes", "Gestionnaire-Matières Premières", "Gestionnaire-Produits semi-finis" }));

        jLabel2.setText("Nom");

        jLabel3.setText("Prénom");

        jLabel4.setText("nom d'utilisateur");

        jLabel5.setText("Mot de passe");

        jLabel6.setText("Grade");

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        btnDéconnecter.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        btnDéconnecter.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnDéconnecter.setText("Déconnecter");
        btnDéconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDéconnecterActionPerformed(evt);
            }
        });

        btnPrevious.setText("<");

        btnNext.setText(">");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                            .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnregistrer)
                                .addGap(16, 16, 16)
                                .addComponent(btnEffacer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrénom)
                                    .addComponent(txtUsername)
                                    .addComponent(txtPassword)
                                    .addComponent(cbxGrade, 0, 0, Short.MAX_VALUE)
                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblGrade, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1)
                        .addContainerGap(245, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(585, Short.MAX_VALUE)
                .addComponent(btnDéconnecter)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAjouter, btnAnnuler, btnEffacer, btnEnregistrer, btnModifier});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel2)
                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel3)
                                    .addComponent(txtPrénom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel4)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel5)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(cbxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(2, 2, 2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(btnModifier)
                                    .addComponent(btnEnregistrer)
                                    .addComponent(btnEffacer)
                                    .addComponent(btnAnnuler)
                                    .addComponent(btnAjouter)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnPrevious)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDéconnecter)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        txtNom.setText("");
        txtPrénom.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        cbxGrade.setSelectedIndex(0);
        saveOrUpdate = true;
        txtNom.requestFocus();
        currentRow = lstUsers.getSelectedIndex();
        buttonEnabler(false);
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        listLoad = false;
        buttonEnabler(true);
        if (cbxGrade.getSelectedItem().toString().equals("Administrateur")) {
            grade = "admin";
        } else if (cbxGrade.getSelectedItem().toString().equals("Gestionnaire-Citernes")) {
            grade = "citerne";
        } else if (cbxGrade.getSelectedItem().toString().equals("Gestionnaire-Matières Premières")) {
            grade = "mat_prm";
        } else if (cbxGrade.getSelectedItem().toString().equals("Gestionnaire-Produits semi-finis")) {
            grade = "prod_sfini";
        }
        if (saveOrUpdate) {
            user = new User(txtNom.getText(), txtPrénom.getText(), txtUsername.getText(), txtPassword.getText(), grade);
            getDaos().getUserDAO().createUser(user);
            JOptionPane.showMessageDialog(null, "Enregistrement effectué", "Enregistrement", JOptionPane.INFORMATION_MESSAGE);
        } else {
            user = getDaos().getUserDAO().getUserByUsername(txtUsername.getText());
            user.setNom(txtNom.getText());
            user.setPrénom(txtPrénom.getText());
            user.setUsername(txtUsername.getText());
            user.setPassword(txtPassword.getText());
            user.setGrade(grade);
            boolean updated = getDaos().getUserDAO().updateUser(user);
            if (updated) {
                JOptionPane.showMessageDialog(null, "Modification effectuée", "Modification", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        listDisplay();
        listLoad = true;
        lstUsers.setSelectedValue(user.getNom() + " " + user.getPrénom(), true);
        lstUsers.requestFocus();
        
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Etes-vous sûr de vouloir supprimer l'utilisateur: " + txtNom.getText(), "Confirmer", JOptionPane.YES_NO_CANCEL_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            int userId = getDaos().getUserDAO().getUserByUsername(txtUsername.getText()).getId();
            boolean deleted = getDaos().getUserDAO().deleteUser(userId);
            if (deleted) {
                JOptionPane.showMessageDialog(null, "Opération effectuée", "Suppression", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        listLoad = false;
        listDisplay();
        lstUsers.setSelectedIndex(0);
        listDetails();
        listLoad = true;
        lstUsers.requestFocus();
        currentRow = lstUsers.getSelectedIndex();
    }//GEN-LAST:event_btnEffacerActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listDisplay();
        listLoad = true;
        lstUsers.setSelectedIndex(0);
        listDetails();
        buttonEnabler(true);
    }//GEN-LAST:event_formWindowOpened

    private void lstUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUsersValueChanged
        if (listLoad == true) {
            listDetails();
        }
    }//GEN-LAST:event_lstUsersValueChanged

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        buttonEnabler(false);
        saveOrUpdate = false;
        currentRow = lstUsers.getSelectedIndex();
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        listLoad = false;
        listDisplay();
        lstUsers.setSelectedIndex(currentRow);
        listDetails();
        buttonEnabler(true);
        listLoad = true;
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnDéconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDéconnecterActionPerformed
        int i = JOptionPane.showConfirmDialog(null, "Voulez-vous quitter l'application?", "Confirmez", JOptionPane.YES_NO_CANCEL_OPTION);
        if (i == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        } else {
            lstUsers.requestFocus();
        }
    }//GEN-LAST:event_btnDéconnecterActionPerformed
    public void fillIn(User user) {
        txtNom.setText(user.getNom());
        txtPrénom.setText(user.getPrénom());
        txtUsername.setText(user.getUsername());
        txtPassword.setText(user.getPassword());
        if (user.getGrade().equals("admin")) {
            selectedItemIndex = 0;
        } else if (user.getGrade().equals("citerne")) {
            selectedItemIndex = 1;
        } else if (user.getGrade().equals("mat_prm")) {
            selectedItemIndex = 2;
        } else if (user.getGrade().equals("prod_sfini")) {
            selectedItemIndex = 3;
        }
        cbxGrade.setSelectedIndex(selectedItemIndex);
        lblGrade.setText(cbxGrade.getSelectedItem().toString());
    }

    public void listDisplay() {
        int i = 1;
        users = getDaos().getUserDAO().getAllUsers();
        listmodel.clear();
        for (User systemUser : users) {
            listmodel.addElement(i+"."+systemUser.getNom().concat(" " + systemUser.getPrénom()));
            ++i;
        }
        lstUsers.setModel(listmodel);
    }

    public void listDetails() {
        int indexOfEmpty = lstUsers.getSelectedValue().toString().indexOf(" ");
        String nom = lstUsers.getSelectedValue().toString().substring(2, indexOfEmpty);
        String prénom = lstUsers.getSelectedValue().toString().substring(indexOfEmpty + 1);
        user = new User();
        user = getDaos().getUserDAO().getUserByNames(nom, prénom);
        fillIn(user);
    }

    public void buttonEnabler(boolean enabler) {
        cbxGrade.setEnabled(!enabler);
        btnEnregistrer.setEnabled(!enabler);
        btnAnnuler.setEnabled(!enabler);
        btnAjouter.setEnabled(enabler);
        btnModifier.setEnabled(enabler);
        btnEffacer.setEnabled(enabler);
        btnDéconnecter.setEnabled(enabler);
        btnPrevious.setEnabled(enabler);
        btnNext.setEnabled(enabler);
        lblGrade.setVisible(enabler);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnDéconnecter;
    private javax.swing.JButton btnEffacer;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JComboBox cbxGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JList lstUsers;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPrénom;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
